proxy:
  image: nginx:alpine
  volumes:
    - ./proxy_nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/acme-webroot:/var/acme-webroot
    - /etc//etc/ssl/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
  ports:
    - "80:80"
    - "443:443"
  restart: unless-stopped

