database:
  image: postgres:9.4
  ports:
    - "15432:5432"
  volumes:
     - ./db:/var/lib/postgresql/data
  restart: unless-stopped
  #environment:
  #   - POSTGRES_PASSWORD=postgres

server:
  build: .
  ports:
    - "8000:80"
  links:
    - database
  volumes:
    - /etc/crt:/etc/letsencrypt/live/xtomo.ru
  #  - ./robotom/logs:/var/www/web/robotom/logs
  restart: unless-stopped
