database:
  image: postgres:9.4
  ports:
    - "15432:5432"
  volumes:
     - ./db:/var/lib/postgresql/data
  restart: unless-stopped
  #environment:
  #   - POSTGRES_PASSWORD=postgres

server:
  build: .
  ports:
    - "5080:80"
  links:
    - database
  external_links:
    - storage_server_1
  # volumes:
  #   - ./robotom/logs:/var/www/web/robotom/logs
  restart: unless-stopped
