database:
  image: postgres:9.4
  ports:
    - "15432:5432"
  volumes:
     - ./db:/var/lib/postgresql/data
  restart: unless-stopped
  #environment:
  #   - POSTGRES_PASSWORD=postgres

server:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
  #  - ./robotom/logs:/var/www/web/robotom/logs
  restart: unless-stopped
